name: openly
description: A modern Flutter app for secure office door access
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.0
  local_auth: ^2.1.7

flutter:
  uses-material-design: true
