name: openly
description: A modern Flutter app for secure office door access
publish_to: "none"
version: 1.7.0+10

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.0
  local_auth: ^2.1.7
  flutter_lints: ^6.0.0
  ota_update: ^7.0.2
  package_info_plus: ^8.3.0
  permission_handler: ^12.0.1
  expressive_loading_indicator: ^0.0.1
  flex_color_picker: ^3.7.1
  pull_to_refresh: ^2.0.0
  flutter_markdown: ^0.7.3
flutter:
  uses-material-design: true
