name: Build Flutter APK

on:
  push:
    branches: [main]
    paths-ignore:
      - ".github/workflows/**"
      - "README.md"
      - ".gitignore"
  workflow_dispatch:

jobs:
  get-next-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - run: npm ci
      - run: npx semantic-release --dry-run
        id: get-next-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      new-release-published: ${{ steps.get-next-version.outputs.new-release-published }}
      new-release-version: ${{ steps.get-next-version.outputs.new-release-version }}
      new-release-git-tag: ${{ steps.get-next-version.outputs.new-release-git-tag }}

  build_and_release:
    runs-on: ubuntu-latest
    needs: get-next-version
    if: needs.get-next-version.outputs.new-release-published == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.1"

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Node dependencies
        run: npm ci

      - name: Decode and save keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/openly-key.jks
          echo "KEYSTORE_PATH=$GITHUB_WORKSPACE/android/app/openly-key.jks" >> $GITHUB_ENV
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEY_ALIAS_PASSWORD=${{ secrets.KEY_ALIAS_PASSWORD }}" >> $GITHUB_ENV

      - name: Build APK (signed)
        run: |
          flutter build apk --release \
            --build-name ${{ needs.get-next-version.outputs.new-release-version }} \
            --build-number ${{ github.run_number }}

      - name: Rename APK with version and build number
        run: |
          VERSION="${{ needs.get-next-version.outputs.new-release-version }}"
          BUILD_NUMBER=${{ github.run_number }}
          mv build/app/outputs/flutter-apk/app-release.apk \
            build/app/outputs/flutter-apk/openly-v${VERSION}+${BUILD_NUMBER}.apk
          echo "RENAMED_APK_PATH=build/app/outputs/flutter-apk/openly-v${VERSION}+${BUILD_NUMBER}.apk" >> $GITHUB_ENV

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
