name: Build Flutter APK

on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/workflows/**'
      - 'README.md'
      - '.gitignore'
  pull_request:
    branches: [main]
  workflow_dispatch:  # 👈 Enables manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Check flutter doctor
        run: flutter doctor -v
      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
